//catalogos centrales del help desk

window.HD_CATALOGOS = {
  FORMAS_SOLICITUD: [
    "E-mail",
    "Telefónico",
    "Whatsapp",
    "Instrucción Gerencia",
    "Otro",
  ],

  TIPOS_SOLICITUD: [
    "Aplicación de Primas",
    "Armar pólizas (Impresión, CG)",
    "Cambio de Contratante",
    "Cambio de Titular",
    "Cancelación - Con dev primas",
    "Cancelación - Sin dev primas",
    "Cotización",
    "Devolución de Primas",
    "Emisión (nueva)",
    "Endoso 1 (alta coberturas-unidades)",
    "Endoso 2 - (baja coberturas-unidades)",
    "Endoso 3 (sin modificación de primas)",
    "Otras",
    "Re-Expedición de Emisión Nueva",
    "Re-Expedición de Renovación",
    "Rehabilitar pólizas/endosos",
    "Renovación",
    "Resello factura",
    "Seguimiento Serie en SISE",
    "Solicitud - BT normal",
    "Solicitud - Clave AMIS",
    "Solicitud - Suma Asegurada",
  ],

  AREAS_DESTINO: [
    "AOF",
    "Caja Metepec",
    "Caja San Jerónimo",
    "OTRS Suscripción Individual",
    "OTRS Valores Convenidos",
    "Plataforma CRM",
    "Devoluciones (Milka)",
    "Control de agentes",
    "Devoluciones OPL",
    "OTR tarifas",
    "Claudia Vázquez (BP)",
    "Cuentas Coorporativas (multianuales)",
    "Suscripción flotillas",
  ],

  AGENTES: [
    { clave: "00203", nombre: "MOISES GARCIA YA&EZ" },
    { clave: "00381", nombre: "EDMUNDO PALOMINO MAGDALENO" },
    { clave: "00424", nombre: "AMADO MAURILIO ROJAS TARANGO" },
    { clave: "00522", nombre: "RAMON LARA PE&A" },
    { clave: "00525", nombre: "SALVADOR RAMIREZ VAZQUEZ" },
    { clave: "00648", nombre: "RAFAEL BUITRON FERNANDEZ" },
    { clave: "01275", nombre: "JUANA GONZALEZ VILLEGAS" },
    { clave: "03066", nombre: "MA. LOURDES MONROY AGUILAR" },
    { clave: "03177", nombre: "ELIA JUDITH ESPINOSA LEDESMA" },
    { clave: "03514", nombre: "RISKMANAGEMENT, AGENTE DE SEGUROS Y DE FIANZAS, S.A. DE C.V."},
    { clave: "03839", nombre: "FRANCISCO BALDERAS GERMAN" },
    { clave: "04350", nombre: "JOSEFINA HERNANDEZ ORTEGA" },
    { clave: "04583", nombre: "MISAEL CRUZ JIMENEZ" },
    { clave: "04652", nombre: "DEMETRIO KUSULAS ZERON" },
    { clave: "04782", nombre: "IRMA SOTO CLEMENTE" },
    { clave: "04965", nombre: "EDWARD LAWRENCE SHAW PHILIPS" },
    { clave: "04976", nombre: "MARIO PEREZ VILCHIS" },
    { clave: "05318", nombre: "LILIA COLIN MUNGUIA" },
    { clave: "05533", nombre: "ALEJANDRO LOPEZ ESTRADA" },
    { clave: "05642", nombre: "RAMON MARTINEZ VENEGAS" },
    { clave: "05699", nombre: "EDUARDO ADRIAN ESCAMILLA MONROY" },
    { clave: "05707", nombre: "MAURICIO OVIEDO JIMENEZ" },
    { clave: "05917", nombre: "JOSE GUADALUPE MOLINAR CABRAL" },
    { clave: "06138", nombre: "OLGA ERIKA SANCHEZ WARNKE" },
    { clave: "06305", nombre: "NORMA ANGELICA RIOS SANDOVAL" },
    { clave: "06674", nombre: "LUIS FELIPE GARCIA ZAVALA" },
    { clave: "06738", nombre: "MIGUEL ROBERTO HERNANDEZ PICHARDO" },
    { clave: "06916", nombre: "JEZABEL CARPIO RAMIREZ" },
    { clave: "06989", nombre: "MARIBEL RAMIREZ MEDINA" },
    { clave: "07317", nombre: "MEGA AUTOMOTRIZ, SA DE CV" },
    { clave: "07391", nombre: "AUTOFINANCIAMIENTO MEXICO, S.A. DE C.V." },
    { clave: "08108", nombre: "MARIA GUADALUPE HERNANDEZ GONZALEZ" },
    { clave: "08300", nombre: "MIGUEL TAFOLLA MALDONADO" },
    { clave: "08440", nombre: "HELITA MONTIEL RODRIGUEZ" },
    { clave: "08472", nombre: "ADRIAN MARTINEZ CUADROS" },
    { clave: "08532", nombre: "JUAN CARLOS MILLAN CORTES" },
    { clave: "08592", nombre: "MARIA DEL CARMEN CERON RODRIGUEZ" },
    { clave: "09005", nombre: "VENTAS MOSTRADOR OFICINA TOLUCA" },
    { clave: "13393", nombre: "MIGUEL ANGEL MENDOZA RIVERA" },
    { clave: "13462", nombre: "ELENA MAGDALENA AYALA PONTON" },
    { clave: "16064", nombre: "JOSE CORAZON TAPIA FERNANDEZ" },
    { clave: "16181", nombre: "LUIS FELIPE GARCIA RODRIGUEZ" },
    { clave: "16312", nombre: "CARLOS ROBERTO GALLEGOS LUNA" },
    { clave: "16550", nombre: "IGNACIO JOSE TERROBA TORTOLERO" },
    { clave: "17498", nombre: "LEON FELIPE BEDOYA MARTINEZ" },
    { clave: "17507", nombre: "JUAN MUCI&O SERRANO" },
    { clave: "17756", nombre: "FABIOLA TELLEZ ESCAMILLA" },
    { clave: "17955", nombre: "SILVIA NASTA VICTORIA" },
    { clave: "17960", nombre: "MA. OLGA BERNAL LAGUNAS" },
    { clave: "22246", nombre: "GILDARDO ZU&IGA MARIN" },
    { clave: "22714", nombre: "RUTILIO PI&A VELAZQUEZ" },
    { clave: "22955", nombre: "MIGUEL ANGEL CEBALLOS AYALA" },
    { clave: "23087", nombre: "JULIO CESAR ROJANO CEPEDA" },
    { clave: "23482", nombre: "CARLOS MANUEL VERONA IZAGUIRRE" },
    { clave: "23732", nombre: "ADMINISTRADORA DE SERV DE CALIDAD AGTE DE SEGUROS SA DE CV"},
    { clave: "24649", nombre: "NIDIA PATINO LONA" },
    { clave: "24869", nombre: "JUAN JOSE BARREIRO PAEZ" },
    { clave: "25202", nombre: "JULIAN EYMAR VENCES ALVAREZ" },
    { clave: "30391", nombre: "PABLO LOPEZ ROSALES" },
    { clave: "30596", nombre: "LILIANA JOSEFINA SANCHEZ SANCHEZ" },
    { clave: "30982", nombre: "IRAN DIAZ ALONSO" },
    { clave: "31192", nombre: "LETICIA HORTENSIA TALAVERA JUAREZ" },
    { clave: "31914", nombre: "MARISOL PAREDEZ CANTAREY" },
    { clave: "35109", nombre: "NORMA PE&A ALMADA" },
    { clave: "35920", nombre: "ANTONIO FERNANDEZ DE JESUS" },
    { clave: "40496", nombre: "PF TOLLOCAN, S.A. DE C.V." },
    { clave: "40497", nombre: "PF TOLLOCAN, S.A. DE C.V." },
    { clave: "40498", nombre: "PF TOLLOCAN, S.A. DE C.V." },
    { clave: "42457", nombre: "METEPEC MOTORS S.A. DE C.V." },
    { clave: "43338", nombre: "VEHICULOS Y SERVICIOS SATELITE,SA DE CV" },
    { clave: "43339", nombre: "VEHICULOS Y SERVICIOS SATELITE,SA DE CV" },
    { clave: "43982", nombre: "SAN MATEO MOTORS SA DE CV" },
    { clave: "43984", nombre: "MEGA AUTOMOTRIZ, SA DE CV" },
    { clave: "44071", nombre: "SANCHEZ AUTOMOTRIZ SA DE CV" },
    { clave: "44432", nombre: "INCOSOL SA DE CV" },
    { clave: "50255", nombre: "GERSON BENJAMIN GONZALEZ ZU&IGA" },
    { clave: "50474", nombre: "ADMINISTRADORA DE SERV DE CALIDAD AGTE DE SEGUROS SA DE CV"},
    { clave: "50726", nombre: "YATZILTH PALACIOS GOICOCHEA" },
    { clave: "52038", nombre: "MARIO GABINO ESTRADA FLORES" },
    { clave: "55454", nombre: "SILVIA NASTA VICTORIA" },
    { clave: "55571", nombre: "BERNARDO ANGULO GONZALEZ" },
    { clave: "56127", nombre: "JOSE URIEL CORZA URIBE" },
    { clave: "56128", nombre: "CECILIO ALFONSO SALAZAR CEBALLOS" },
    { clave: "56250", nombre: "MANUEL RABINDRANATH ESCALERA MERAZ" },
    { clave: "57841", nombre: "MOISES GARCIA YA&EZ" },
    { clave: "58560", nombre: "GRUPO AFSE DE MEXICO AGENTE DE SEGUROS Y DE FIANZAS SA DE CV"},
    { clave: "58775", nombre: "LUCINA GARCIA GONZALEZ" },
    { clave: "59323", nombre: "SALVADOR RAMIREZ VAZQUEZ" },
    { clave: "59596", nombre: "GRUPO RCM AGENTE DE SEGUROS Y DE FIANZAS, S.A. DE C.V."},
    { clave: "59664", nombre: "JUAN CARLOS ROSSANO SERRANO" },
    { clave: "60428", nombre: "ALFREDO ALEJO BECERRIL" },
    { clave: "61117", nombre: "ALFREDO SORDO AGUILAR" },
    { clave: "61194", nombre: "NOEMI CARDENAS ESPINOZA" },
    { clave: "61222", nombre: "SALVADOR LOPEZ JIMENEZ" },
    { clave: "61357", nombre: "CESAR SANCHEZ SANCHEZ DE TAGLE" },
    { clave: "61384", nombre: "MARIA LEISLY MARTINEZ LOPEZ" },
    { clave: "61419", nombre: "FRANCISCA ORTIZ MENDOZA" },
    { clave: "61485", nombre: "ALFONSO ERICK SANCHEZ ESCARCEGA" },
    { clave: "61545", nombre: "EFREN ESTRADA VELAZQUEZ" },
    { clave: "61549", nombre: "EDGAR ALEJANDRO AGUILAR NAVARRETE" },
    { clave: "61550", nombre: "GUADALUPE ZOE SOLEDAD GOMEZ RAMIREZ" },
    { clave: "61605", nombre: "SALVADOR LOPEZ JIMENEZ" },
    { clave: "61606", nombre: "FRANCISCA ORTIZ MENDOZA" },
    { clave: "61696", nombre: "JESUS RUBEN RIOS ROBLEDO" },
    { clave: "61801", nombre: "AIME VALDES ECHEVERRIA" },
    { clave: "61927", nombre: "YOSELIN PASCACIO NUNEZ" },
    { clave: "61948", nombre: "GUADALUPE ZOE SOLEDAD GOMEZ RAMIREZ" },
    { clave: "62017", nombre: "TANIA CRISTINA JIMENEZ RUIZ" },
    { clave: "62032", nombre: "MARIA DEL CONSUELO ZU&IGA ZATARAIN" },
    { clave: "62302", nombre: "FERNANDO MACARIO ROMERO" },
    { clave: "62379", nombre: "TANIA MAYA LOPEZ" },
    { clave: "62471", nombre: "RAFAEL MAX RAMOS CALDERON" },
    { clave: "62837", nombre: "GUILLERMO MENDOZA NU&EZ" },
    { clave: "63825", nombre: "VICTOR HUGO PIMENTEL FLORES" },
    { clave: "64093", nombre: "MARCO ANTONIO CABALLERO MATEOS" },
    { clave: "64178", nombre: "GERMAN ZOE NAVARRO LOPEZ" },
    { clave: "64293", nombre: "JUAN ALBERTO ORDO&EZ LARA" },
    { clave: "64494", nombre: "MARIA JUANA FERMIN CONTRERAS" },
    { clave: "64510", nombre: "TERESA AVELAR LOPEZ" },
    { clave: "64546", nombre: "JOSE LUIS MEDINA GONZALEZ" },
    { clave: "64578", nombre: "IVAN GARCIA GUADARRAMA" },
    { clave: "64592", nombre: "ESTHELA REYES HERNANDEZ" },
    { clave: "64598", nombre: "BEATRIZ SANTANA BECERRIL" },
    { clave: "64660", nombre: "LUCRECIA LOZANO CRUZ" },
    { clave: "64871", nombre: "EFREN LINARES ESTRADA" },
    { clave: "64899", nombre: "MARCO ANTONIO ZAMUDIO LOPEZ" },
    { clave: "65068", nombre: "CLAUDIA NATALIA NU&EZ ESPARZA" },
    { clave: "65279", nombre: "FRANCO AGUILAR NAVA" },
    { clave: "65336", nombre: "LUIS MAURICIO TELLEZ ESCAMILLA" },
    { clave: "65434", nombre: "RICARDO ISRAEL RODRIGUEZ ARTEAGA" },
    { clave: "65436", nombre: "GLORIA IVONNE ESPARZA DURAN" },
    { clave: "65444", nombre: "JOSUE CURIEL NERI" },
    { clave: "65534", nombre: "JOSE LUIS MARTINEZ ORDO&EZ" },
    { clave: "65543", nombre: "CECILIA VILCHIS PORCAYO" },
    { clave: "66053", nombre: "KAREN CARMIN HARO PEREZ" },
    { clave: "66848", nombre: "FABIOLA RAMIREZ BERMUDEZ" },
    { clave: "66903", nombre: "JOSE GERARDO SALDA&A VALDES" },
    { clave: "66962", nombre: "SBHEIDY ESCAMILLA DORANTES" },
    { clave: "67066", nombre: "KAREN IVETTE PLATA REYES" },
    { clave: "67161", nombre: "JOSE LUIS GUTIERREZ OLGUIN" },
    { clave: "67322", nombre: "RAMON ESTEBAN MENDEZ CASTANEDA" },
    { clave: "67500", nombre: "EDGAR ALEJANDRO AGUILAR NAVARRETE" },
    { clave: "67508", nombre: "KARLA IVONNE MACEDO CUENCA" },
    { clave: "67530", nombre: "PERLA JANNET RANGEL JIMENEZ" },
    { clave: "67549", nombre: "MARTIN GONZALEZ NAVA" },
    { clave: "67979", nombre: "GUSTAVO ALBERTO ROJAS ESPINOSA" },
    { clave: "68163", nombre: "KARINA PEREZ PEDRAL" },
    { clave: "68292", nombre: "MUSOL MONROY CASTRO" },
    { clave: "68543", nombre: "MAURICIO GARZA GARCIA" },
    { clave: "68644", nombre: "ROBERTO ESPINOZA MONTES DE OCA" },
    { clave: "69064", nombre: "Andrea Melissa Rincon Trejo" },
    { clave: "69288", nombre: "ANAID LARA MENDOZA" },
    { clave: "70180", nombre: "EDUARDO KICK CERVANTES" },
    { clave: "70219", nombre: "JUAN GARCIA GARCIA" },
    {
      clave: "70237",
      nombre: "AON RISK SOLUTIONS,AGENTE DE SEGUROS Y DE FIANZAS,S.A.DE C.V",
    },
    { clave: "71763", nombre: "LILIANA JOSEFINA SANCHEZ SANCHEZ" },
    { clave: "71827", nombre: "SERGIO ARRIETA ALDACO" },
    { clave: "72216", nombre: "THELMA YOLANDA ESTRADA HIDALGO" },
    {
      clave: "72844",
      nombre: "AON RISK SOLUTIONS,AGENTE DE SEGUROS Y DE FIANZAS,S.A.DE C.V",
    },
    { clave: "73943", nombre: "AURELIANO SANCHEZ CUEVAS" },
    { clave: "74564", nombre: "JAVIER ESPINOZA DOMINGUEZ" },
    { clave: "74609", nombre: "HECTOR CARLOS GARZA GUERRA" },
    { clave: "74894", nombre: "YAZMIN RETANA MORENO" },
    { clave: "74978", nombre: "LUIS EDUARDO CHAPARRO SANCHEZ" },
    { clave: "75066", nombre: "ANA LILIA SALDA&A SANCHEZ" },
    { clave: "75109", nombre: "NADIA CAROLYNE BAUTISTA BARAJAS" },
    { clave: "75650", nombre: "JORGE MORENO CRIVELLI" },
    {
      clave: "75828",
      nombre: "SMART RESOLVIENDO TU VIDA, AGENTE DE SEGUROS S.A. DE C.V.",
    },
    { clave: "75919", nombre: "RICARDO MORALES MARTINEZ" },
    { clave: "76497", nombre: "JUAN EMILIO RAMOS CALDERON" },
    { clave: "77013", nombre: "FERNANDO GARCIA ESTRADA" },
    { clave: "77610", nombre: "CYNTIA TERESA ZALDIVAR RADILLA" },
    { clave: "77871", nombre: "GEORGINA ORTEGA ORTIZ" },
    { clave: "77935", nombre: "MERCEDES GOMEZ FLORES" },
    { clave: "77965", nombre: "RAMON LARA PE&A" },
    { clave: "77966", nombre: "RAMON LARA PE&A" },
    { clave: "77967", nombre: "RAMON LARA PE&A" },
    { clave: "78379", nombre: "LILIANA MARIA GUTIERREZ GONZALEZ" },
    { clave: "78502", nombre: "JUAN MANUEL LINARES CORTES" },
    { clave: "78651", nombre: "LUCERO FLORES ORTIZ" },
    { clave: "78901", nombre: "FRANCISCO JAVIER NU&EZ GUTIERREZ" },
    { clave: "79045", nombre: "GLADYS ZULMIRA APONTE MENDEZ" },
    { clave: "79078", nombre: "GABRIELA SIERRA MARTINEZ" },
    { clave: "79271", nombre: "RAFAEL REBOLLAR FERNANDEZ" },
    { clave: "79374", nombre: "ARNULFO ALVA RUIZ" },
    { clave: "79669", nombre: "ALEJANDRO BENITEZ GARCIA" },
    { clave: "79941", nombre: "ERIK BERNARDO CERON FLORES" },
    { clave: "80110", nombre: "OSCAR AARON MARTINEZ GARCIA" },
    { clave: "80947", nombre: "LILIANA RUBIO CARBAJAL" },
    { clave: "81083", nombre: "ERIK BERNARDO CERON FLORES" },
    { clave: "81097", nombre: "RUBEN CRUZ MARTINEZ" },
    { clave: "82220", nombre: "ERIK BERNARDO CERON FLORES" },
    { clave: "82290", nombre: "RAFAEL REBOLLAR FERNANDEZ" },
    {
      clave: "82440",
      nombre: "GRUPO RCM AGENTE DE SEGUROS Y DE FIANZAS, S.A. DE C.V.",
    },
    { clave: "82736", nombre: "RAFAEL REBOLLAR FERNANDEZ" },
    { clave: "82809", nombre: "DANIELA ROBLES CARPIO" },
    { clave: "82821", nombre: "MA. LOURDES MONROY AGUILAR" },
    {
      clave: "83053",
      nombre: "IINSURED BROKERS,AGENTE DE SEGUROS Y DE FIANZAS,S.A DE C.V",
    },
    { clave: "83591", nombre: "OMAR GARCIA GUADARRAMA" },
    { clave: "83873", nombre: "JOSE URIEL CORZA URIBE" },
    { clave: "84558", nombre: "IRVING ESQUIVEL ONTIVEROS" },
    { clave: "85512", nombre: "BERENICE SOLIS VAZQUEZ" },
    { clave: "85635", nombre: "ABDEL PATRICIA DE LA TORRE PEREZ" },
    {
      clave: "86091",
      nombre: "KOI, AGENTE DE SEGUROS Y DE FIANZAS, S.A. DE C.V.",
    },
    { clave: "86534", nombre: "MONICA AMELIA GARCIA MARTINEZ" },
    { clave: "86801", nombre: "ARTURO ANGEL SAINZ LOPEZ" },
    { clave: "86918", nombre: "EDUARDO KICK CERVANTES" },
    {
      clave: "86948",
      nombre: "MARSH MEXICO, AGENTE DE SEGUROS Y DE FIANZAS, SA DE CV",
    },
    { clave: "87260", nombre: "TANIA MAYA LOPEZ" },
    { clave: "87354", nombre: "ANGEL RODRIGO REYES LUNA" },
    { clave: "87622", nombre: "JOEL JACINTO DELGADO" },
    { clave: "87781", nombre: "FABRICIA LEON LEON" },
    { clave: "87941", nombre: "JUAN CARLOS BOBADILLA DIAZ" },
    { clave: "87942", nombre: "RENE OMAR TORTI RIOS" },
    { clave: "87950", nombre: "JOSE MARIO LOPEZ ITURBIDE" },
    { clave: "88178", nombre: "ARTURO ISAAC RAMIREZ VALDESPINO" },
    { clave: "88189", nombre: "HYLANT MEXICO AGTE DE SEG Y DE FZAS SA D" },
    { clave: "88199", nombre: "HYLANT MEXICO AGTE DE SEG Y DE FZAS SA D" },
    { clave: "88200", nombre: "HYLANT MEXICO AGTE DE SEG Y DE FZAS SA D" },
    { clave: "88201", nombre: "HYLANT MEXICO AGTE DE SEG Y DE FZAS SA D" },
    { clave: "88203", nombre: "MAURICIO ORTIZ GONZALEZ" },
    { clave: "88340", nombre: "MARCO AURELIO CEBALLOS CORONA" },
    {
      clave: "88362",
      nombre: "INBROS, AGENTE DE SEGUROS Y DE FIANZAS S.A. DE C.V.",
    },
    { clave: "88494", nombre: "DONATO EMMANUEL SANTOS MATEO" },
    { clave: "88591", nombre: "JUAN RAUL TAPIA GRISI" },
    { clave: "88832", nombre: "VER NICA JACKELINE GARCIA SOLORIO" },
    { clave: "88876", nombre: "EDER ANDREY LUQUES GAMEZ" },
    { clave: "88877", nombre: "ERICKA SANDOVAL ALVAREZ" },
    { clave: "89050", nombre: "IRENE DE JESUS MORALES SALAZAR" },
    { clave: "89055", nombre: "NORMA ANGELICA RIOS SANDOVAL" },
    { clave: "89056", nombre: "NORMA ANGELICA RIOS SANDOVAL" },
    { clave: "89395", nombre: "ALICIA MONZERRAT MALANCO SIERRA" },
    { clave: "89504", nombre: "ALY CORANY ABDALLAH" },
    { clave: "89612", nombre: "QUITZIA ZEPEDA DIAZ" },
    { clave: "89738", nombre: "MIGUEL ANGEL GOMEZ CASTILLO" },
    { clave: "90218", nombre: "QUALITAS COMPA&IA DE SEGUROS S.A. DE C.V." },
    { clave: "90265", nombre: "QUALITAS COMPA&IA DE SEGUROS S.A. DE C.V." },
    { clave: "90392", nombre: "QUALITAS COMPA&IA DE SEGUROS S.A. DE C.V." },
    { clave: "90490", nombre: "VENTAS MOSTRADOR OFICINA TOLUCA" },
    { clave: "96147", nombre: "QUALITAS COMPA&IA DE SEGUROS S.A. DE C.V." },
    { clave: "96282", nombre: "QUALITAS COMPA&IA DE SEGUROS S.A. DE C.V." },
    { clave: "90392", nombre: "QUALITAS COMPA&IA DE SEGUROS S.A. DE C.V" },
    { clave: "68702", nombre: "NABOR FRANCISCO GONZÁLEZ AGUILAR" },
    { clave: "27855", nombre: "MONICA LOPEZ SORIANO" },
    { clave: "28535", nombre: "SAMUEL RUIZ SANCHEZ" },
    { clave: "28586", nombre: "Gerardo Lobo Treviño" },
    { clave: "28583", nombre: "Christian Hernández Valdes" },
  ],
};
